Repository kartikayasijaa/talk-trove, pull requests merged in 2024-10, with the labels that each got.

#17 #Add Greetings.yml
  .github/workflows/Greetings.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#20 Additon of All Contributors | Issue #19
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#30 ADD : Responsiveness to main page #28
  frontend/src/components/Chatbox.js
  frontend/src/components/MyChats.js
  frontend/src/components/SingleChat.js
  frontend/src/components/miscellaneous/SideDrawer.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#22 methods are made for emai template and email confirigation using gmail smtp server
  backend/controllers/userControllers.js
  backend/mailtrap/emailTemplates.js
  backend/mailtrap/emails.js
  backend/mailtrap/mailtrap.config.js
  backend/routes/userRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#37 Removed default react icon from website
  frontend/public/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#63 fix mongodb connection error
  backend/scripts/seed.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#69 add sample env files
  README.md
  backend/.env.sample
  frontend/.env.sample
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#77 added emoji feature
  frontend/package.json
  frontend/src/components/SingleChat.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#82 Added Mute and unmute feature
  backend/models/chatModel.js
  backend/routes/chatRoutes.js
  frontend/src/components/MyChats.js
  frontend/src/components/SingleChat.js
  frontend/yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level3

#83 add package lock json
  frontend/yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level2

#88 Update README.md
  README.md
Labels: documentation, good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#104 Fixed Add github workflows
  .github/workflows/Greetings.yml
  .github/workflows/autocomment-iss-close.yml
  .github/workflows/autocomment-iss-raise.yml
  .github/workflows/autocomment-pr-merge.yml
  .github/workflows/autocomment-pr-raise.yml
  .github/workflows/close-old-issue.yml
  .github/workflows/close-old-pr.yml
  .github/workflows/greetings.yml
Labels: gssoc-ext, hacktoberfest-accepted, level3

#105 fix the position of chat indicator, updated
  frontend/src/components/SingleChat.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#58 fix chat icon
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: gssoc-ext, level1, hacktoberfest

#47 #38 issue Add Docker Setup for Frontend and Backend
  backend/.dockerignore
  backend/config/db.js
  docker-compose.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#31 [Feat] Added forget password feature
  backend/.env.sample
  backend/controllers/userControllers.js
  backend/models/ResetOTPModel.js
  backend/package.json
  backend/routes/userRoutes.js
  backend/utils/helpers/emailService.js
  backend/utils/helpers/generateOtp.js
  backend/yarn.lock
  frontend/src/App.js
  frontend/src/Pages/ForgotPassPage.js
  frontend/src/Pages/ResetPassPage.js
  frontend/src/components/Authentication/ForgotPassword.js
  frontend/src/components/Authentication/Login.js
  frontend/src/components/Authentication/ResetPassword.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#117 Fix form disabling on api call
  frontend/src/components/Authentication/Login.js
  frontend/src/components/Authentication/Signup.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#122 Revamp signup form
  frontend/src/components/Authentication/Signup.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#130 [Feature Request]: Adding preview of links shared to chat with click property
  backend/controllers/messageControllers.js
  backend/models/messageModel.js
  backend/yarn.lock
  frontend/src/components/ScrollableChat.js
  frontend/yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level3

#140 [Feature Request]: Adding Contributors count with slideshow
  .github/workflows/contibutors.yml
  .vaunt/cards/contributors.svg
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1
